name: connectme
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^7.9.2
  flutter_riverpod: ^2.6.1
  graphql_flutter: ^5.1.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fpdart: ^1.1.1
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^6.1.0 
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^7.3.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
