name: connectme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  auto_route: ^9.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  dio: ^5.4.0
  shared_preferences: ^2.3.3
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  internet_connection_checker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
